name: midnight_suspense
description: listen to bengali audio stories anytime, all the time.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ^3.4.0

dependencies:
  bloc: ^8.1.3
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.0
  flutter_bloc: ^8.1.4
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0

dev_dependencies:
  build_runner: ^2.4.11
  bloc_test: ^9.1.6
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.3
  very_good_analysis: ^6.0.0

  flutter_gen_runner: ^5.6.0
  device_preview: ^1.2.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/
