name: midnight_suspense
description: listen to bengali audio stories anytime, all the time.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ^3.4.0

dependencies:
  animations: ^2.0.11
  audio_service: ^0.18.15
  audio_session: ^0.1.21
  bloc: ^8.1.3
  cached_network_image: ^3.3.1
  collection: ^1.18.0
  cronet_http: ^1.3.2
  cupertino_http: ^1.5.1
  dio: ^5.5.0+1
  fl_chart: ^0.69.0
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.0
  flutter_bloc: ^8.1.4
  flutter_dotenv: ^5.1.0
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^2.0.10+1
  freezed_annotation: ^2.4.4
  get_it: ^7.7.0
  google_fonts: ^6.2.1
  gradient_borders: ^1.0.1
  http: ^1.2.2
  intl: ^0.19.0
  isar:
    version: 3.1.8
    hosted: https://pub.isar-community.dev/
  isar_flutter_libs: # contains Isar Core
    version: 3.1.8
    hosted: https://pub.isar-community.dev/
  json_annotation: ^4.9.0
  just_audio: ^0.9.39
  loading_animation_widget: ^1.2.1
  logger: ^2.4.0
  page_transition: ^2.1.0
  path_provider: ^2.1.4
  rxdart: ^0.28.0
  scroll_to_hide: ^2.1.0
  ticker_text: ^2.1.0
  youtube_explode_dart: ^2.2.1

dev_dependencies:
  build_runner: ^2.4.11
  bloc_test: ^9.1.6
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.3
  very_good_analysis: ^6.0.0
  flutter_gen_runner: ^5.6.0
  device_preview: ^1.2.0
  freezed: ^2.5.2
  json_serializable: ^6.8.0
  isar_generator:
    version: 3.1.8
    hosted: https://pub.isar-community.dev/

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/
    - assets/icons/

flutter_gen:
  output: lib/src/gen/ # Optional (default: lib/gen/)
  line_length: 110 # Optional (default: 80)

  # Optional
  integrations:
    flutter_svg: true
    # flare_flutter: true
    # rive: true
    # lottie: true
